import {secondary, primary} from '../../../assets/getColors';
export const stepIndicatorStyle = {
  stepIndicatorSize: 30,
  currentStepIndicatorSize: 40,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 2,
  stepStrokeCurrentColor: secondary,
  stepStrokeWidth: 1,
  stepStrokeFinishedColor: secondary,
  stepStrokeUnFinishedColor: 'gray',
  separatorUnFinishedColor: 'gray',
  separatorFinishedColor: secondary,
  stepIndicatorFinishedColor: secondary,
  stepIndicatorUnFinishedColor: '#ffffff',
  stepIndicatorCurrentColor: '#ffffff',
  stepIndicatorLabelFontSize: 0,
  currentStepIndicatorLabelFontSize: 0,
  stepIndicatorLabelCurrentColor: secondary,
  stepIndicatorLabelFinishedColor: '#ffffff',
  stepIndicatorLabelUnFinishedColor: '#aaaaaa',
  labelColor: '#999999',
  labelSize: 13,
  currentStepLabelColor: primary,
};
